allowBuilds:
    '@parcel/watcher': true
    '@swc/core': true
    esbuild: true
    msw: true
    sharp: true
    unrs-resolver: true
ignoredBuiltDependencies:
    - sharp
    - unrs-resolver
minimumReleaseAgeExclude:
    - esbuild@0.24.3
    - postcss@8.5.10
    - qs@6.15.2
overrides:
    esbuild@<=0.24.2: ^0.25.0
    postcss@<8.5.10: ^8.5.10
    qs@>=6.11.1 <=6.15.1: ^6.15.2
