ALTER TABLE "distros" ALTER COLUMN "docs_url" SET DEFAULT '{}';--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "docs_url" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "total_reviews" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "ux_experience_rating" SET DEFAULT '0';--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "ux_experience_rating" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "performance_rating" SET DEFAULT '0';--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "performance_rating" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "stability_rating" SET DEFAULT '0';--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "stability_rating" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "features_rating" SET DEFAULT '0';--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "features_rating" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "support_rating" SET DEFAULT '0';--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "support_rating" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "distro_type" SET DEFAULT '{}';--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "distro_type" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "based_on" SET DEFAULT '{}';--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "based_on" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "origin_country" SET DEFAULT '{}';--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "origin_country" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "architectures" SET DEFAULT '{}';--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "architectures" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "desktop_environments" SET DEFAULT '{}';--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "desktop_environments" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "categories" SET DEFAULT '{}';--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "categories" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "status" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "description" SET DEFAULT '';--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "description" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "source_url" SET DEFAULT '{}';--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "source_url" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "taken_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "distros" ALTER COLUMN "updated_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "distros" ADD COLUMN "slug" varchar(100) NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "idx_distros_slug" ON "distros" USING btree ("slug");--> statement-breakpoint
ALTER TABLE "distros" ADD CONSTRAINT "distros_slug_unique" UNIQUE("slug");