ALTER TABLE "bayesian_results" ALTER COLUMN "shrinkage_coefficient" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "bayesian_results" ALTER COLUMN "confidence_adjusted_score" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "penalty_results" ALTER COLUMN "distance_normalized" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "penalty_results" ALTER COLUMN "penalty_value" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "penalty_results" ALTER COLUMN "utility_score" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_meta" ALTER COLUMN "denominator_ux" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_meta" ALTER COLUMN "denominator_performance" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_meta" ALTER COLUMN "denominator_stability" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_meta" ALTER COLUMN "denominator_features" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_meta" ALTER COLUMN "denominator_support" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_meta" ALTER COLUMN "positive_ux" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_meta" ALTER COLUMN "positive_performance" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_meta" ALTER COLUMN "positive_stability" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_meta" ALTER COLUMN "positive_features" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_meta" ALTER COLUMN "positive_support" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_meta" ALTER COLUMN "negative_ux" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_meta" ALTER COLUMN "negative_performance" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_meta" ALTER COLUMN "negative_stability" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_meta" ALTER COLUMN "negative_features" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_meta" ALTER COLUMN "negative_support" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_result" ALTER COLUMN "normalized_ux" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_result" ALTER COLUMN "normalized_performance" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_result" ALTER COLUMN "normalized_stability" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_result" ALTER COLUMN "normalized_features" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_result" ALTER COLUMN "normalized_support" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_result" ALTER COLUMN "weighted_ux" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_result" ALTER COLUMN "weighted_performance" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_result" ALTER COLUMN "weighted_stability" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_result" ALTER COLUMN "weighted_features" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_result" ALTER COLUMN "weighted_support" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_result" ALTER COLUMN "distance_ideal_positive" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_result" ALTER COLUMN "distance_ideal_negative" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "topsis_result" ALTER COLUMN "cc_score" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "weight_survey" ALTER COLUMN "ux_weight" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "weight_survey" ALTER COLUMN "performance_weight" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "weight_survey" ALTER COLUMN "stability_weight" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "weight_survey" ALTER COLUMN "features_weight" SET DATA TYPE numeric(14, 12);--> statement-breakpoint
ALTER TABLE "weight_survey" ALTER COLUMN "support_weight" SET DATA TYPE numeric(14, 12);